# Site wide configuration
locale                   : "en-US"
encoding                 : UTF-8
title                    : "Home"
title_separator          : "-"
name                     : &name "Wilson Mar"
description              : &description "I have a dream..."
url                      : https://wilsonmar.github.io
gh_repo                  : "https://github.com/wilsonmar/wilsonmar.github.io"
github:
   repo:  https://github.com/wilsonmar/wilsonmar.github.io
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

comments:
  provider               : "disqus" # false (default), "disqus", "facebook", "google-plus", custom"
  disqus:
    shortname            : "minimalmistakes" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"

# SEO Related
google_site_verification : "8KG_Ns5zQokAg5smIfVDhCRFzkYkpUfCi-SXm-vWU2A"
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Conversion:

# Markdown Processing:
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: false


# Social Sharing
twitter:
  username               : &twitter "wilsonmar"
facebook:
  username               : &facebook "wilsonmar"
  app_id                 :
  publisher              :
og_image                 : "site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/wilsonmar"
    - "https://facebook.com/wilsonmar"

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-2011187-3"

# Google AdSense
google_ad_client         :
google_ad_slot           :

# Site owner/author:
owner:
  name: Wilson Mar
  avatar: wilsonmar_2009.jpg
  bio: "Hello. Hire me!"
  email: wilsonmar@gmail.com
  phone: 310 320-7878
  citrix: MTYzMDs3NDc=-ak2yo1dniypx1ree0398hj3d61raszy7bg5xce1137dfjcqnl0mfp52ygs1fwnom
  disqus-shortname: wilsonmargithubio
  twitter: wilsonmar
  gitter: wilsonmar
  skype: wilsonmar4
  facebook: 
  google:
    plus: WilsonMar1
    analytics:
    verify: 8KG_Ns5zQokAg5smIfVDhCRFzkYkpUfCi-SXm-vWU2A
    ad-client:
    ad-slot:
  bing-verify: 73A60A207FC7D42B6F428E462079B002
  github: wilsonmar
  stackoverflow: 112099/wilson-mar
  linkedin: wilsonmar
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: wilsonmar4
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: wilsonmar
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

collections:
- us-states